<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        /*
            콜백 지옥 (callback hell, callback chain)
            : 함수의 매개변수로 넘겨지는 콜백 함수가 반복되는 현상 
            : 코드의 들여쓰기 수준이 깊어짐 (가독성 ↓)
        */

        function add(x, callback){ // callback: 함수
            let sum = x + x;
            console.log(sum);
            callback(sum);
        }

        add(2, function(res){
            add(res, function(res){
                add(res, function(res){
                    console.log('finish!');
                })
            })
        })

        // 1) Promise (약속)
        // : 콜백 함수를 잘 정리해놓으면 나중에 불러줄게!
        // - 상태: pending (중지) -> fullfilled (만족) or rejected (거절)
        // - producer (생산자) vs consumer (소비자)
        
        // : Promise가 정상 수행 resolve()
        // :               실패 reject() 

        // 1-1) Producer
        // const promise = new Promise((resolve, reject) => {
        //        // ...........
        // });
        // : Promise는 생성되면 바로 실행
        const promise = new Promise((resolve, reject) => {
            // resolve('success!');
            reject(new Error('no network ...'));
        });

        // 1-2) Consumer
        // : then (resolve()), catch (reject()), 
        // finally (수행 결과와 상관없이 무조건 실행)
        promise
        .then((value)=>console.log(value)) // resolve()
        // 에러 잡음 (프로그램 중단 X (***))
        .catch((error)=>console.log(error)) // reject()
        .finally(()=>console.log('finally!'));

        console.log('here!!! 1'); // 출력이 될까요 ..?
        console.log('here!!! 2'); // 출력이 될까요 ..?
        console.log('here!!! 3'); // 출력이 될까요 ..?


        function add(x, callback){ // callback: 함수
            let sum = x + x;
            console.log(sum);
            callback(sum);
        }

        add(2, function(res){
            add(res, function(res){
                add(res, function(res){
                    console.log('finish!');
                })
            })
        })

        function add_promise(x){ 
            return new Promise((resolve, reject) => {
                let sum = x + x;
                console.log(sum);
                resolve(sum);
            })
        }

        add_promise(2).then(res => {
            add_promise(res).then(res => {
                add_promise(res).then(res => {
                    console.log('finish!!');
                })
            })
        })

        // promise에 return 사용하면 callback hell 탈출!
        add_promise(2).then(res => {
            return add_promise(res);
        }).then(res => {
            return add_promise(res);
        }).then(res => {
            console.log('finish!!');
        })
    </script>
</body>
</html>